name: ci

on:
  push:
    branches: [main]
    tags: "*"
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-${{ matrix.os }}-${{ matrix.deno }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: [v1.x, canary]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}

      - run: deno --version

      - name: Format
        if: runner.os == 'Linux'
        run: deno fmt --check

      - name: Lint
        if: runner.os == 'Linux'
        run: deno lint

      - name: Run tests
        run: deno test -A

      - name: Dry run publishing
        if: runner.os == 'Linux' && matrix.deno == 'canary'
        run: deno publish --dry-run

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - run: deno --version

      - name: Publish (on tag)
        run: deno publish
